[tools]
erlang = "latest"
node = "latest"
pnpm = "latest"
gleam = "latest"
spago = "latest"
purescript = "latest"

[tasks]
build = "pnpm run build"
dev = "pnpm run dev"
lint = "pnpm run lint"
format = "pnpm run format"
check-types = "pnpm run check-types"
test = "pnpm run test"
